//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editor3DFigures
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string Path { get; set; }
        public string UserLogin { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
